apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp-container
        # Jenkins will dynamically update 'latest' to the actual build number
        image: vishalskayande121/webapp:latest
        ports:
        - containerPort: 80
        imagePullPolicy: Always
